apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver-service
spec:
  type: NodePort
  ports:
    - name: web
      port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    app: airflow-webserver

