apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadtester-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadtester
  template:
    metadata:
      labels:
        app: loadtester
    spec:
      containers:
      - name: loadtester
        image: shadowmen2169/taller_ci_loadtester:27c6c79a217d2691bb1c169473a95dbbb6ee87c0