apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadtester-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadtester
  template:
    metadata:
      labels:
        app: loadtester
    spec:
      containers:
      - name: loadtester
        image: shadowmen2169/taller_ci_loadtester:6566287388b92a719e0cf8d5e640a83ebd9b91ca