---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      nodeSelector:
        kubernetes.io/hostname: noam02
      containers:
      - name: mlflow
        image: shadowmen2169/proyecto_4_mlflow:58709e47024fb361b06702c933a1edba0a404049
        command:
          - mlflow
          - server
          - --backend-store-uri
          - mysql+pymysql://$(MLFLOW_MYSQL_USER):$(MLFLOW_MYSQL_PASSWORD)@mysql-mlflow-service:3306/$(MLFLOW_MYSQL_DATABASE)
          - --default-artifact-root
          - s3://mlflows3/artifacts
          - --host
          - 0.0.0.0
          - --serve-artifacts
        env:
        - name: MLFLOW_S3_ENDPOINT_URL
          valueFrom:
            secretKeyRef:
              name: project-secrets
              key: MLFLOW_S3_ENDPOINT_URL
        - name: MLFLOW_TRACKING_URI
          valueFrom:
            secretKeyRef:
              name: project-secrets
              key: MLFLOW_TRACKING_URI
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: project-secrets
              key: MINIO_ROOT_USER
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: project-secrets
              key: MINIO_ROOT_PASSWORD
        - name: MLFLOW_MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: project-secrets
              key: MLFLOW_MYSQL_USER
        - name: MLFLOW_MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: project-secrets
              key: MLFLOW_MYSQL_PASSWORD
        - name: MLFLOW_MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: project-secrets
              key: MLFLOW_MYSQL_DATABASE
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
spec:
  type: NodePort
  ports:
    - name: mlflow
      port: 5000
      targetPort: 5000
      nodePort: 30500
  selector:
    app: mlflow
