apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: proyecto-4
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/JorgeArdila2169/MLOps_2510
    targetRevision: main
    path: proyecto_4/k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
