apiVersion: v1
kind: Service
metadata:
  name: gradio-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 8503
      targetPort: 8503
      nodePort: 30850 
  selector:
    app: gradio

