apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-config
data:
  datasource.yaml: |
    apiVersion: 1

    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://10.43.101.201:30910
        isDefault: true
