apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
spec:
  type: NodePort
  ports:
    - name: mlflow
      port: 5000
      targetPort: 5000
      nodePort: 30500
  selector:
    app: mlflow
