version: '3.8'

services:

  mlops_env:
    build: .
    container_name: mlops_env
    restart: always
    volumes:
      - .:/app
    command: tail -f /dev/null  # Mantiene el contenedor corriendo sin salir
 
  mysql:
    image: mysql:8.0
    container_name: mysql_mlops
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mlflow_db
      MYSQL_USER: mlflow_user
      MYSQL_PASSWORD: mlflow_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  minio:
    image: minio/minio
    container_name: minio_mlops
    restart: always
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.1.0
    container_name: mlflow_mlops
    restart: always
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
    ports:
      - "5000:5000"
    command: mlflow server --backend-store-uri mysql://mlflow_user:mlflow_pass@mysql/mlflow_db --default-artifact-root s3://mlflow/ --host 0.0.0.0
    depends_on:
      - mysql
      - minio

  airflow:
    image: apache/airflow:2.5.0
    container_name: airflow_mlops
    restart: always
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    ports:
      - "8080:8080"
    command: webserver
    depends_on:
      - mysql

  api_inferencia:
    build: ./api_inferencia
    container_name: api_inferencia_mlops
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mlflow

volumes:
  mysql_data:
  minio_data:

