version: "3.8"

services:
  locust:
    build:
      context: .
      dockerfile: Dockerfile.locust
    ports:
      - "8089:8089"
    networks:
      - my_network

networks:
  my_network:
    external: true