version: "3.8"

services:
  api:
    image: shadowmen2169/mlops:latest
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 300M
    networks:
      - locust_network

networks:
  locust_network:
    external: true
    name: locust_network