# Docker Compose para JupyterLab
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jupyter_env
    volumes:
      - ./notebooks:/app/notebooks
      - ./transformation_files:/app/transformation_files
      - ./data_cleaned:/app/data_cleaned
      - ./pipeline:/app/pipeline
    ports:
      - "8888:8888"
    command: ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--allow-root", "--NotebookApp.notebook_dir=/app", "--NotebookApp.token=''"]
