apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-data
  template:
    metadata:
      labels:
        app: mysql-data
    spec:
      containers:
      - name: mysql
        image: mysql:8
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: project-secrets
              key: DATA_MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: project-secrets
              key: DATA_MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: project-secrets
              key: DATA_MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: project-secrets
              key: DATA_MYSQL_PASSWORD
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-data-pvc

