apiVersion: v1
kind: Service
metadata:
  name: mysql-data-service
spec:
  type: NodePort
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      nodePort: 30316
  selector:
    app: mysql-data
