name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      IMAGE_API_BASE: ${{ secrets.DOCKERHUB_USERNAME }}/taller_ci_api
      IMAGE_LOADTESTER_BASE: ${{ secrets.DOCKERHUB_USERNAME }}/taller_ci_loadtester
      GIT_EMAIL: "jorgemario2169@gmail.com"  
      GIT_NAME: "Jorge Ardila"                  

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies for API training
      run: |
        python -m pip install --upgrade pip
        pip install scikit-learn

    - name: Train model
      working-directory: taller_ci_cd/api
      run: python train_model.py

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }}

    - name: Build and push API image with tag
      working-directory: taller_ci_cd/api
      run: |
        IMAGE_TAG=${{ github.sha }}
        docker build -t $IMAGE_API_BASE:$IMAGE_TAG .
        docker push $IMAGE_API_BASE:$IMAGE_TAG
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    - name: Build and push LoadTester image with tag
      working-directory: taller_ci_cd/loadtester
      run: |
        IMAGE_TAG=${{ github.sha }}
        docker build -t $IMAGE_LOADTESTER_BASE:$IMAGE_TAG .
        docker push $IMAGE_LOADTESTER_BASE:$IMAGE_TAG

    - name: Update deployment manifests with new image tags and push
      run: |
        IMAGE_TAG=${{ github.sha }}
        MANIFEST_API="taller_ci_cd/manifests/api-deployment.yaml"
        MANIFEST_LOADTESTER="taller_ci_cd/manifests/script-deployment.yaml"

        sed -i "s|\($IMAGE_API_BASE:\).*|\1$IMAGE_TAG|" $MANIFEST_API
        sed -i "s|\($IMAGE_LOADTESTER_BASE:\).*|\1$IMAGE_TAG|" $MANIFEST_LOADTESTER

        git config user.email "${{ env.GIT_EMAIL }}"
        git config user.name "${{ env.GIT_NAME }}"

        git add $MANIFEST_API $MANIFEST_LOADTESTER
        git commit -m "Update image tags to $IMAGE_TAG [skip ci]" || echo "No changes to commit"

        git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}
        git push origin HEAD:main