name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      IMAGE_API: ${{ secrets.DOCKERHUB_USERNAME }}/taller_ci_api:latest
      IMAGE_LOADTESTER: ${{ secrets.DOCKERHUB_USERNAME }}/taller_ci_loadtester:latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies for API training
      run: |
        python -m pip install --upgrade pip
        pip install scikit-learn

    - name: Train model
      working-directory: taller_ci_cd/api
      run: python train_model.py

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }}

    - name: Build and push API image
      working-directory: taller_ci_cd/api
      run: |
        docker build -t $IMAGE_API .
        docker push $IMAGE_API

    - name: Build and push LoadTester image
      working-directory: taller_ci_cd/loadtester
      run: |
        docker build -t $IMAGE_LOADTESTER .
        docker push $IMAGE_LOADTESTER